In [9]:
%load_ext autoreload
%autoreload 2
from notebook.services.config import ConfigManager
cm = ConfigManager().update('notebook', {'limit_output': None})

import tensorflow as tf
from old_src.turboae_adapters.encoder_decoders import load_tf_turboae_encoder
from src.factories import turboae_exact_nonsys_bd
from src.interleaver import TurboAEInterleaver

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
ENCODER_PATH = "../turboae_models/222877_dta_steq2_cnn2_cnn5_enctrain2_dectrainneg15_2_enc.pt"
turboae_encoder = load_tf_turboae_encoder(ENCODER_PATH)

In [3]:
exact_encoder = turboae_exact_nonsys_bd(interleaver=TurboAEInterleaver(), block_len=100, delay=2)

In [22]:
from src.datasets import binary_messages
dataset = binary_messages(1, block_len=100, num_batches=100)


In [24]:
data = []
for data_batch in dataset:
    exact_enc_out = exact_encoder(data_batch.value)
    exact_enc_out = tf.reshape(exact_enc_out["output"].value, (100, 3))
    tae_out = turboae_encoder(data_batch.value)
    tae_out = (tf.reshape(tae_out, (100, 3)) + 1) / 2
    data.append([data_batch.value, tf.reduce_all(exact_enc_out == tae_out).numpy()])


    

In [25]:
tensors, match = zip(*data)

In [27]:
tensors[0]

<tf.Tensor: shape=(1, 100, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [

In [28]:
enc_out = tf.reshape(exact_encoder(tensors[0])["output"].value, (100, 3))
tae_out = (tf.reshape(turboae_encoder(tensors[0]), (100, 3)) + 1) / 2

In [32]:
enc_out == tae_out
tensors[0][0, 97:, 0]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 1., 0.], dtype=float32)>

In [33]:
tae_out[99]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 0., 0.], dtype=float32)>

In [34]:
enc_out[99]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>

In [35]:
enumerate_binary_inputs(3)

NameError: name 'enumerate_binary_inputs' is not defined