In [51]:
%load_ext autoreload
%autoreload 2

import numpy as np
from src.utils import enumerate_binary_inputs, dec2bitarray, bitarray2dec
from pprint import pprint

WINDOW = 9
assert WINDOW % 2 == 1
print(WINDOW)
print(WINDOW // 2 + 1)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
9
5


In [53]:
tae_outputs = np.load("../turboae_models/test_tae.npy")
tae_outputs_incorrect = np.load("../turboae_models/test_tae_incorrect.npy")

In [54]:
tae_outputs.shape

(512, 9, 3)

In [55]:
bin_inputs = enumerate_binary_inputs(WINDOW).numpy()

In [56]:
main_outputs = tae_outputs[:, WINDOW // 2 + 1, :]

In [57]:
result = np.empty((WINDOW, WINDOW, 3))
for i in range(WINDOW):
    # bin_inputs is 2^W x W
    inputs_i_0 = bin_inputs[(bin_inputs[:, i] == 0)]  # Which of the 2^W is bit i == 0
    inds_i_0 = bitarray2dec(inputs_i_0, little_endian=False).numpy()
    assert np.all(inds_i_0 == np.arange(2 ** WINDOW)[(bin_inputs[:, i] == 0)])
    
    inputs_i_1 = np.array(inputs_i_0, copy=True)
    inputs_i_1[:, i] += 1
    inds_i_1 = bitarray2dec(inputs_i_1, little_endian=False).numpy()
    result[i] = np.mean((tae_outputs[inds_i_0] != tae_outputs[inds_i_1]).astype(np.float32), axis=0)
result
    

array([[[1.    , 1.    , 1.    ],
        [0.    , 0.    , 0.875 ],
        [0.9375, 1.    , 0.5   ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ]],

       [[0.    , 0.    , 0.5   ],
        [1.    , 1.    , 0.875 ],
        [0.8125, 1.    , 1.    ],
        [0.9375, 1.    , 0.5   ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ]],

       [[0.    , 1.    , 0.5   ],
        [0.    , 0.    , 0.875 ],
        [0.8125, 1.    , 0.5   ],
        [0.8125, 1.    , 1.    ],
        [0.9375, 1.    , 0.5   ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ],
        [0.    , 0.    , 0.    ]],

       [[0.    , 0.    , 0.    ],
        [0.    , 1.    , 0.875 ],
        

In [37]:
result[:, 4]

array([[0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    ],
       [0.9375, 1.    , 0.5   ],
       [0.8125, 1.    , 1.    ],
       [0.8125, 1.    , 0.5   ],
       [0.8125, 0.    , 1.    ],
       [0.9375, 1.    , 1.    ],
       [0.    , 0.    , 0.    ],
       [0.    , 0.    , 0.    ]])

In [23]:
np.arange(2 ** 9)[(bin_inputs[:, i] == 0)]
inds_i_0

<tf.Tensor: shape=(256,), dtype=int32, numpy=
array([  0, 256, 128, 384,  64, 320, 192, 448,  32, 288, 160, 416,  96,
       352, 224, 480,  16, 272, 144, 400,  80, 336, 208, 464,  48, 304,
       176, 432, 112, 368, 240, 496,   8, 264, 136, 392,  72, 328, 200,
       456,  40, 296, 168, 424, 104, 360, 232, 488,  24, 280, 152, 408,
        88, 344, 216, 472,  56, 312, 184, 440, 120, 376, 248, 504,   4,
       260, 132, 388,  68, 324, 196, 452,  36, 292, 164, 420, 100, 356,
       228, 484,  20, 276, 148, 404,  84, 340, 212, 468,  52, 308, 180,
       436, 116, 372, 244, 500,  12, 268, 140, 396,  76, 332, 204, 460,
        44, 300, 172, 428, 108, 364, 236, 492,  28, 284, 156, 412,  92,
       348, 220, 476,  60, 316, 188, 444, 124, 380, 252, 508,   2, 258,
       130, 386,  66, 322, 194, 450,  34, 290, 162, 418,  98, 354, 226,
       482,  18, 274, 146, 402,  82, 338, 210, 466,  50, 306, 178, 434,
       114, 370, 242, 498,  10, 266, 138, 394,  74, 330, 202, 458,  42,
       298, 170, 4

In [58]:
pprint(tae_outputs.tolist())

[[[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 1, 1],
  [1, 1, 1]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 0, 1],
  [0, 1, 0],
  [1, 1, 1],
  [0, 0, 0]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 0, 1],
  [0, 1, 0],
  [0, 0, 0],
  [0, 0, 0],
  [1, 1, 1]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [1, 0, 1],
  [0, 1, 0],
  [1, 1, 1],
  [0, 0, 0],
  [0, 0, 0]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [0, 1, 0],
  [0, 0, 0],
  [1, 1, 0],
  [1, 1, 1],
  [1, 0, 1]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [0, 1, 0],
  [0, 0, 0],
  [0, 0, 1],
  [1, 1, 1],
  [0, 1, 0]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [0, 1, 0],
  [1, 1, 1],
  [1, 1, 1],
  [0, 0, 0],
  [1, 0, 1]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [1, 0, 1],
  [0, 1, 0],
  [1, 1, 1],
  [0, 0, 0],
  [0, 0, 0],
  [0, 1, 0]],
 [[1, 1, 1],
  [1, 1, 1],
  [1, 0, 1],
  [0, 1, 0],
  [0

In [49]:
enumerate_binary_inputs(3)


<tf.Tensor: shape=(8, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 1],
       [0, 1, 0],
       [0, 1, 1],
       [1, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 1, 1]], dtype=int32)>

In [50]:
import tensorflow as tf
bitarray2dec(
    tf.pad(
        enumerate_binary_inputs(3),
        [[0, 0], [2, 0]],
    )[:, :3]
)

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int32)>

In [ ]:
tf.gather(
    TURBOAE_EXACT_TABLE[:, i, :2],
    bitarray2dec(
        tf.pad(
            enumerate_binary_inputs(window)[:, : i - main_ind],
            [[0, 0], [main_ind - i, 0]],
        )
    ),
    axis=0,
),
num_steps=1,
delay=delay,
)
for i in range(main_ind)