In [2]:
import tensorflow as tf
from src.datasets import binary_messages

In [3]:
dataset = binary_messages(batch_size=1, block_len=3)

In [4]:
new_dataset = dataset.take(5)

In [5]:
for i in new_dataset:
    print(i)

(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 1., 1.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 1.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 0.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[1., 0., 0.]], dtype=float32)>,)


In [6]:
for i in new_dataset:
    print(i)

(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 1., 1.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 1.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 0., 1.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 1., 1.]], dtype=float32)>,)
(<tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0., 1., 0.]], dtype=float32)>,)


In [1]:
%load_ext autoreload
%autoreload 2

from src.channels import AdditiveTOnAWGN

In [2]:
a = AdditiveTOnAWGN(snr=1.0)
a.name

'additive_t_on_awgn'